### ISSUE TITLE
Support subdirectories

### ISSUE THREAD

**Issue by abompard** [fedora-python/tox-github-action#16]
I have multiple python packages in subdirectories in my repository, each having a `tox.ini` file. It would be useful to me if I could ask `tox-github-action` to cd to a subdirectory before running tox.

**Comment by hroncok** [comment]
A support for this (via an environment variable, such as `$WORKDIR`) would need to be added to https://github.com/fedora-python/fedora-python-tox/blob/master/run_tests.sh first.

**Comment by hroncok** [comment]
Then, we could pass it via this:

https://github.com/fedora-python/tox-github-action/blob/9f7d1fff53d7384568baa0ddd748e0c35b102b82/action.yaml#L15-L17

**Comment by frenzymadness** [comment]
This is now implemented in the container image so we can prepare it here.
