### ISSUE TITLE
Future versioning

### ISSUE THREAD

**Issue by frenzymadness** [fedora-python/tox-github-action#18]
Because Fedora 34 is almost EOL and Fedora 35 does not contain Python 3.5, we have to find a way how to make it possible to use older versions of fedora-python-tox container image with this GH action. The necessary change of the container images itself is ready here: https://github.com/fedora-python/fedora-python-tox/pull/57

Current usage: grep.app has found [five](https://grep.app/search?q=fedora-python/tox-github-action%40v&filter[lang][0]=YAML) users of `@v0.4` and [eighteen](https://grep.app/search?q=fedora-python/tox-github-action%40master&filter[lang][0]=YAML) users of `@master` which both now means the latest container image.

Proposal:
1. Release version `34` of this action, hardcode the `:34` manifest in it, and document that the versions are the same as the versions of underlying Fedora releases.
2. Wait for a while for the fedora-python-tox based on Fedora 35.
3. Switch the action to Fedora 35 and release version `35`.
4. Add a changelog so users can easily identify what's new in the new version and decide whether they can switch or not.

If we need to change anything in the action itself, we can then release versions like `35.1`.

**Comment by frenzymadness** [comment]
I'd honestly rather use tags. Who wants the latest and greatest can always use the master branch. For others, it's IMHO better to have some control over the versions you use without automatic updates.

**Comment by hroncok** [comment]
Both work for me. We can start with tags and when we release 35.x for the n-th time, we might reconsider, or not. Not many changes were required here in the past, so I don't suspect we would need to "release" often.

**Comment by frenzymadness** [comment]
This is done. I'm gonna release v35.1 soon.
