### ISSUE TITLE
Conscious Language: Please, rename master branch to main branch

### ISSUE THREAD

**Issue by droideck** [fedora-python/tox-github-action#24]
As part of the conscious language effort, the master branch is to be renamed to the main branch. Please, consider the rename for your project as its branch is used and is specified in other projects' workflows.

Here are the instructions:

- Rename the master branch to main: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch
- Check this to ensure the default branch has been changed to main: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch - this should keep the github history, as well as updating the default branch configuration and updating any existing PRs

Thank you!

**Comment by frenzymadness** [comment]
If we rename the branch, what will happen to all the projects using `uses: fedora-python/tox-github-action@master` in their CI configurations?

**Comment by hroncok** [comment]
IIRC at least originally it was possible to rename the branch and keep the old one aliased.

**Comment by frenzymadness** [comment]
The documentation is clear, if you rename a branch, Github adds automatic redirect from the old name to the new one but it does not apply to Gihub Actions, see https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch#about-renaming-branches 

According to grep.app, there are 22 projects with the `uses: fedora-python/tox-github-action@master` in their workflows: https://grep.app/search?q=uses%3A%20fedora-python/tox-github-action%40master

**Comment by hroncok** [comment]
Could we perhaps create a GitHub action here, that keeps the old branch synchronized with the new?

**Comment by frenzymadness** [comment]
I'd rather rename master to main, do a one-time push of a master branch to keep it working, and then open 22 PRs. I'll take a look at it. When done, we can remove the master branch.

**Comment by frenzymadness** [comment]
Exactly half of the PRs are already merged.

**Comment by frenzymadness** [comment]
6 PRs left to be merged:

- [ ] https://github.com/redhat-aqe/kafka-logging-handler/pull/35
- [ ] https://github.com/varlink/python/pull/35
- [ ] https://github.com/matthew-brett/nb2plots/pull/25
- [ ] https://github.com/fedora-infra/datagrepper/pull/598
- [ ] https://github.com/fedora-infra/flask-healthz/pull/96
- [ ] https://github.com/fedora-infra/tahrir/pull/462
- [ ] https://github.com/fedora-infra/supybot-fedora/pull/95
- [ ] https://github.com/fedora-infra/fedora-messaging/pull/284

**Comment by frenzymadness** [comment]
I sent a comment to the open PRs and give them one more month before I remove the master branch.

**Comment by frenzymadness** [comment]
The master branch has just been removed. I think we gave them enough time to respond.

**Comment by encukou** [comment]
grep.app apparently doesn't index everything; `freezeyt` didn't get a PR: https://github.com/encukou/freezeyt/pull/358
